
apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  # This name that will be used within the kubernetes cluster
  name: db
spec:
  # NDB server specific details
  ndb:
    # Cluster id of the cluster where the Database has to be provisioned
    # Can be fetched from the GET /clusters endpoint
    clusterId: 3bdff1b0-faf3-4ed0-b423-aee3273d0415 
    # Credentials secret name for NDB installation
    # data: username, password, 
    # stringData: ca_certificate
    credentialSecret: your-ndb-secret
    # The NDB Server
    server: https://10.42.168.55:8443/era/v0.9
    # Set to true to skip SSL verification, default: false.
    skipCertificateVerification: true
  # Database instance specific details (that is to be provisioned)
  databaseInstance:
    # The database instance name on NDB
    databaseInstanceName: PostgresNKEInstance
    # Names of the databases on that instance
    databaseNames:
      - postgresnke
    # Credentials secret name for NDB installation
    # data: password, ssh_public_key
    credentialSecret: your-db-secret
    size: 10
    timezone: UTC
    type: postgres 
